### ISSUE TITLE
SEB Win released without RSS Feed update

### ISSUE THREAD

**Issue by jeroenhabets** [SafeExamBrowser/SafeExamBrowser-Website#14]
Hi,
We rely on your SEB RSS feed to be notified of new SEB releases: https://sourceforge.net/p/seb/news/feed.rss

I just discovered that the latest Windows release 3.2 June 7th is NOT in the SEB RSS feed.

(I hope you have not abandoned this feed)

Thanks in advance!
Jeroen Habets

**Comment by jeroenhabets** [comment]
I just received a notification (and checked the feed) so it's fixed now. Thanks!

**Comment by danschlet** [comment]
Yes, we updated the RSS feed now. Looks like the Windows updates need to be better coordinated with the RSS news feed and our Twitter account https://twitter.com/safeexambrowser, where we're also making such (and more developer oriented) announcements. Thanks for letting us know!

**Comment by jeroenhabets** [comment]
@danschlet It seems to me that the RSS lacks the Windows release from October 22, 2021 again...

P.S. + FYI: also no post on twitter

**Comment by danschlet** [comment]
Yes, because @dbuechel communicated the release at 18:30 local time on Friday and we live in a country where employees are protected from having to work on weekends. Also we usually communicate releases in the afternoon of our time zone, as then the work day already started for parts of the American continents.

If you want to know about releases the second we publish them, I would recommend to watch the GitHub releases pages.

**Comment by jeroenhabets** [comment]
@danschlet Thank you! I had returned from leave and overlooked the short time between release and my reopening of this ticket :hugs: ! Apologies for appearing impatient. Your hard work is much much appreciated :rocket: :muscle: !

**Comment by jeroenhabets** [comment]
@danschlet (@dbuechel) FYI SEB 3.3.2 for Windows has been released a week ago. I hope you don't mind me notifying you.
